const data = [
  {
    level: "1.1",
    title: "Subject Pronouns",
    tag: "I, you, he, she it, we, you, they, subject pronouns",
    url: "/levels/flashcard.php?set_number=1_1",
  },
  {
    level: "1.2",
    title: "Possessive Adjectives",
    tag: "my, your, his, her, its, our, your, their, possessive adjectives",
    url: "",
  },
  {
    level: "1.3",
    title: "To be",
    tag: "I am, you are, he is, she is, it is, we are, you are, they are, to be",
    url: "",
  },
  {
    level: "1.4",
    title: "To have",
    tag: "have, has",
    url: "",
  },
  {
    level: "1.5",
    title: "This, that, these, those",
    tag: "this, that, these, those",
    url: "",
  },
  {
    level: "1.6",
    title: "Present Simple statements",
    tag: "I live, you live, he lives, present simple, tenses",
    url: "",
  },
  {
    level: "1.7",
    title: "Present Simple questions and negatives",
    tag: "do, does, is, am, are, present simple, tenses, questions",
    url: "",
  },
  {
    level: "1.8",
    title: "Object Pronouns",
    tag: "me, you, her, him, it, us, them, object pronouns",
    url: "",
  },
  {
    level: "1.9",
    title: "a, an, the, some",
    tag: "a, an, the, some",
    url: "",
  },
  {
    level: "1.10",
    title: "Cardinal Numbers 0-100",
    tag: "one, two, three, ten, twenty, a hundred, cardinal numbers",
    url: "",
  },
  {
    level: "2.1",
    title: "Time",
    tag: "five o'clock, a quarter to, five past, am, pm, time",
    url: "",
  },
  {
    level: "2.2",
    title: "Adverbs of frequency",
    tag: "always, usually, often, sometimes, never, adverbs of frequency",
    url: "",
  },
  {
    level: "2.3",
    title: "Wh questions + Present Simple",
    tag: "who, which, why, when, what, how, present simple, questions, tenses",
    url: "",
  },
  {
    level: "2.4",
    title: "There is, There are + Prepositions of Place",
    tag: "there is, there are, in, on, under, behind, above, in front of, prepositions",
    url: "",
  },
  {
    level: "2.5",
    title: "Cardinal Numbers >100",
    tag: "a hundred, a thousand, a million, cardinal numbers",
    url: "",
  },
  {
    level: "2.6",
    title: "Present Continuous",
    tag: "ing, present continuous, tenses, questions",
    url: "",
  },
  {
    level: "2.7",
    title: "Present Simple vs. Present Continuous",
    tag: "works vs. working, present simple, present continuous, tenses",
    url: "/levels/flashcard.php?set_number=2_7",
  },
  {
    level: "2.8",
    title: "Wh questions + Present Continuous",
    tag: "ing, present continuous, questions, tenses",
    url: "/levels/flashcard.php?set_number=2_8",
  },
  {
    level: "2.9",
    title: "Ordinal Numbers",
    tag: "first, second, third, fourth, ordinal numbers",
    url: "/levels/flashcard.php?set_number=2_9",
  },
  {
    level: "2.10",
    title: "Can, Could",
    tag: "can, could, modal verbs",
    url: "/levels/flashcard.php?set_number=2_10",
  },
  {
    level: "3.1",
    title: "Present Simple - third person",
    tag: "is, has, goes, does, teaches, kisses, cries, present simple, tenses, third person, -s, questions",
    url: "/levels/flashcard.php?set_number=3_1",
  },
  {
    level: "3.2",
    title: "Possessive Pronouns",
    tag: "mine, yours, his, hers, its, ours, yours, theirs, possessive pronouns",
    url: "/levels/flashcard.php?set_number=3_2",
  },
  {
    level: "3.3",
    title: "Reflexive pronouns",
    tag: "myself, yourself, himself, herself, itself, ourselves, yourselves, themselves, reflexive pronouns",
    url: "/levels/flashcard.php?set_number=3_3",
  },
  {
    level: "3.4",
    title: "Future Simple",
    tag: "will, future simple, tenses, questions",
    url: "/levels/flashcard.php?set_number=3_4",
  },
  {
    level: "3.5",
    title: "Going to",
    tag: "going to, future, tenses, questions",
    url: "/levels/flashcard.php?set_number=3_5",
  },
  {
    level: "3.6",
    title: "Wh questions - Future Simple/ Going to",
    tag: "who, which, why, when, what, how, future simple, going to, questions, tenses",
    url: "/levels/flashcard.php?set_number=3_6",
  },
  {
    level: "3.7",
    title: "Past Simple - was, were",
    tag: "was, were, to be, past simple, tenses, questions",
    url: "/levels/flashcard.php?set_number=3_7",
  },
  {
    level: "3.8",
    title: "Past Simple - regular verbs",
    tag: "liked, played, watched, worked, past simple, tenses, regular verbs, questions",
    url: "/levels/flashcard.php?set_number=3_8",
  },
  {
    level: "3.9",
    title: "Past Simple - irregular verbs",
    tag: "went, saw, flew, wrote, read, came, past simple, irregular verbs, tenses, questions",
    url: "/levels/flashcard.php?set_number=3_9",
  },
  {
    level: "3.10",
    title: "Past Simple - Wh questions",
    tag: "who, which, why, when, what, how, past simple, questions, tenses",
    url: "/levels/flashcard.php?set_number=3_10",
  },
  {
    level: "4.1",
    title: "Countable nouns - a, an, some, any",
    tag: "a, an, some, any, countable nouns",
    url: "/levels/flashcard.php?set_number=4_1",
  },
  {
    level: "4.2",
    title: "Uncountable nouns - some, any",
    tag: "some, any, uncountable nouns",
    url: "",
  },
  {
    level: "4.3",
    title: "A lot of, a few, many, much",
    tag: "a lot of, a few, many, much",
    url: "",
  },
  {
    level: "4.4",
    title: "Modal verbs - can, could",
    tag: "can, could, can't, couldn't, modal verbs",
    url: "",
  },
  {
    level: "4.5",
    title: "Modals verbs - should, shouldn't",
    tag: "should, shouldn't, modal verbs, questions",
    url: "",
  },
  {
    level: "4.6",
    title: "Modal verbs - must/have to, don't have to",
    tag: "must, have to, has to, don't have to, doesn't have to, modal verbs, questions",
    url: "",
  },
  {
    level: "4.7",
    title: "Modal verbs - mustn't, don't have to",
    tag: "mustn't, don't have to, modal verbs, questions",
    url: "",
  },
  {
    level: "4.8",
    title: "Modals - can, should, must, have to",
    tag: "can, should, must, have to, modal verbs, questions",
    url: "",
  },
  {
    level: "4.9",
    title: "Imperative - instructions",
    tag: "Stop!, Go!, Stay!, imperative, instructions",
    url: "",
  },
  {
    level: "4.10",
    title: "And, but, so, because",
    tag: "and, but, so, because, linking words",
    url: "",
  },
  {
    level: "5.1",
    title: "Make vs. Do - collocations",
    tag: "make, do, collocations",
    url: "/levels/flashcard.php?set_number=5_1",
  },
  {
    level: "5.2",
    title: "Get - collocations",
    tag: "get, collocations",
    url: "",
  },
  {
    level: "5.3",
    title: "A few, few, a little, little",
    tag: "few, a few, little, a little",
    url: "",
  },
  {
    level: "5.4",
    title: "Adjectives - more, less, as...as",
    tag: "adjectives, less, more, bigger, the best",
    url: "",
  },
  {
    level: "5.5",
    title: "Adjectives -ing/ -ed",
    tag: "adjectives, interested, interesting, -ed, -ing",
    url: "",
  },
  {
    level: "5.6",
    title: "Adjectives and adverbs",
    tag: "adjectives, adverbs, quick, quickly, nice, nicely",
    url: "",
  },
  {
    level: "5.7",
    title: "Adjectives and adverbs - grading",
    tag: "adjectives, adverbs, nicer, more nicely",
    url: "",
  },
  {
    level: "5.8",
    title: "Borrow vs. Lend",
    tag: "borrow, lend",
    url: "",
  },
  {
    level: "5.9",
    title: "Too, enough, very",
    tag: "too, very, enough, strong enough, enough money",
    url: "",
  },
  {
    level: "5.10",
    title: "Tell vs. Say - collocations",
    tag: "tell, say, collocations",
    url: "",
  },
  {
    level: "6.1",
    title: "Present Perfect",
    tag: "present perfect, have, has, third verb form, irregular verbs, tenses, questions",
    url: "/levels/flashcard.php?set_number=6_1",
  },
  {
    level: "6.2",
    title: "Present Perfect - just, already, yet",
    tag: "present perfect, just, already, yet, tenses, questions",
    url: "",
  },
  {
    level: "6.3",
    title: "Present Perfect - since, for",
    tag: "present perfect, since, for, tenses, questions",
    url: "",
  },
  {
    level: "6.4",
    title: "Present Perfect - been, gone",
    tag: "present perfect, been, gone, tenses, questions",
    url: "",
  },
  {
    level: "6.5",
    title: "Present Perfect vs. Past Simple",
    tag: "present perfect, past simple, tenses, questions",
    url: "",
  },
  {
    level: "6.6",
    title: "Irregular Verbs 1",
    tag: "irregular verbs",
    url: "",
  },
  {
    level: "6.7",
    title: "Irregular Verbs 2",
    tag: "irregular verbs",
    url: "",
  },
  {
    level: "6.8",
    title: "Irregular Verbs 3",
    tag: "irregular verbs",
    url: "",
  },
  {
    level: "6.9",
    title: "Love, like, enjoy + ing",
    tag: "love, like, enjoy, not mind, hate, -ing",
    url: "",
  },
  {
    level: "6.10",
    title: "State Verbs",
    tag: "state verbs, see, seeing, look, looking, smell, smelling",
    url: "",
  },
  {
    level: "7.1",
    title: "So vs. such",
    tag: "so, such",
    url: "/levels/flashcard.php?set_number=7_1",
  },
  {
    level: "7.2",
    title: "Relative Pronouns",
    tag: "who, which, where, when, why, whose, whom, that",
    url: "",
  },
  {
    level: "7.3",
    title: "Past Continuous",
    tag: "past continuous, was doing, were going, tenses, questions",
    url: "",
  },
  {
    level: "7.4",
    title: "Past Continuous vs. Past Simple",
    tag: "past continuous, past simple, tenses, questions",
    url: "",
  },
  {
    level: "7.5",
    title: "Used to",
    tag: "used to, past, tenses, questions",
    url: "",
  },
  {
    level: "7.6",
    title: "Used to/ Would/ Past Continuous",
    tag: "used to, would, past simple, past continuous, tenses, questions",
    url: "",
  },
  {
    level: "7.7",
    title: "Future - three options",
    tag: "future simple, going to, present continuous, tenses, questions",
    url: "",
  },
  {
    level: "7.8",
    title: "Auxiliary Verbs - Present Tenses",
    tag: "do you, does she, is she, are they, have you, has he, tenses, helping verbs, present simple, present continuous, present perfect",
    url: "",
  },
  {
    level: "7.9",
    title: "Auxiliary Verbs - Past Tenses",
    tag: "did you, I did, were they, were we, tenses, helping verbs, past simple, past continuous, used to, would",
    url: "",
  },
  {
    level: "7.10",
    title: "Auxiliary Verbs - Future Tenses",
    tag: "will you, I will, are you, tenses, helping verbs, going to, future simple, present continuous",
    url: "",
  },
  {
    level: "8.1",
    title: "Me too, me neither",
    tag: "me too, me neither, agree, disagree, opinion",
    url: "/levels/flashcard.php?set_number=8_1",
  },
  {
    level: "8.2",
    title: "Stop, try, remember, regret, forget",
    tag: "stop, try, go on, remember, regret, forget, infinitive, verbs",
    url: "",
  },
  {
    level: "8.3",
    title: "Present Perfect Continuous",
    tag: "present perfect continuous, -ing, tenses, questions",
    url: "",
  },
  {
    level: "8.4",
    title: "Future Continuous",
    tag: "tenses, future continuous, future simple, going to, questions",
    url: "",
  },
  {
    level: "8.5",
    title: "Predictions - present and future (must, may, might, could, should)",
    tag: "predictions, present, future, must, may, might, could, should",
    url: "",
  },
  {
    level: "8.6",
    title: "Deduction - past (must, may, might, could, should)",
    tag: "deduction, past, must, may, might, could, should",
    url: "",
  },
  {
    level: "8.7",
    title: "Past Perfect",
    tag: "past perfect, tenses, had had, questions",
    url: "",
  },
  {
    level: "8.8",
    title: "Past Perfect Continuous",
    tag: "past perfect continuous, tenses, had been doing, questions",
    url: "",
  },
  {
    level: "8.9",
    title: "Have/Get sth done",
    tag: "have sth done, get sth done",
    url: "",
  },
  {
    level: "8.10",
    title: "Can vs. Be able to",
    tag: "can, be able to, modals",
    url: "",
  },
  {
    level: "9.1",
    title: "First and Zero Conditional plus Unless",
    tag: "first conditional, second conditional, if, unless",
    url: "/levels/flashcard.php?set_number=9_1",
  },
  {
    level: "9.2",
    title: "Second Conditional",
    tag: "second conditional, if, unless",
    url: "",
  },
  {
    level: "9.3",
    title: "Third Conditional",
    tag: "third conditional, if, unless",
    url: "",
  },
  {
    level: "9.4",
    title: "Question Tags - Present",
    tag: "question tags, present, is it, am I, aren't I, do, does, have",
    url: "",
  },
  {
    level: "9.5",
    title: "Question Tags - Past",
    tag: "question tags, past, did, was, were",
    url: "",
  },
  {
    level: "9.6",
    title: "Question Tags - Future and Modals",
    tag: "question tags , future, will, going to, will you",
    url: "",
  },
  {
    level: "9.7",
    title: "Future Perfect and Future Perfect Continuous",
    tag: "future perfect, future perfect continuous, will, will have",
    url: "",
  },
  {
    level: "9.8",
    title: "Clauses of Contrast, Purpose, Reason",
    tag: "althought, even though, despite, in spite of, however, in order to, since, so as to, because, due to",
    url: "",
  },
  {
    level: "9.9",
    title: "Wishes - Present",
    tag: "wish, present",
    url: "",
  },
  {
    level: "9.10",
    title: "wish, past",
    tag: "wish, past",
    url: "",
  },
  {
    level: "10.1",
    title: "Used to, be used to, get used to",
    tag: "used to, be used to, get used to",
    url: "/levels/flashcard.php?set_number=9_1",
  },
  {
    level: "10.2",
    title: "Likely, Unlikely",
    tag: "likely, unlikely, probable, predictions",
    url: "",
  },
  {
    level: "10.3",
    title: "Passive Voice - Present Tenses",
    tag: "passive voice, present, tenses",
    url: "",
  },
  {
    level: "10.4",
    title: "Passive Voice - Past Tenses",
    tag: "passive voice, past, tenses",
    url: "",
  },
  {
    level: "10.5",
    title: "Passive Voice - Future Tenses",
    tag: "passive voice, future, tenses",
    url: "",
  },
  {
    level: "10.6",
    title: "Passive Voice with Modal Verbs",
    tag: "passive voice, modal verbs",
    url: "",
  },
  {
    level: "10.7",
    title: "Indirect Questions",
    tag: "indirect questions, who, which, why, when, what, how",
    url: "",
  },
  {
    level: "10.8",
    title: "Subject/Object Questions",
    tag: "subject questions, object questions, who, which, why, when, what, how",
    url: "",
  },
  {
    level: "10.9",
    title: "Reported Speech",
    tag: "reported speech, indirect speech, said, told",
    url: "",
  },
  {
    level: "10.10",
    title: "Reporting Verbs and Distancing",
    tag: "reporting verbs, distancing, it is said, it is thought, believe, announce, report, claim, expect, suggest",
    url: "",
  },
];

export default data;
