export const cards2_1 = [
  {
    id: "1",
    front: "Która jest godzina?",
    back: "What time is it?",
    image: "img/levels/level_2/set_2_1/whattime.jpg",
  },
  {
    id: "2",
    front: "O której godzinie wstajesz?",
    back: "What time do you get up?",
    image: "",
  },
  {
    id: "3",
    front: "Jest równa dziewiąta.",
    back: "It's 9 o'clock.",
    image: "",
  },
  {
    id: "4",
    front: "Jest w pół do jedenastej.",
    back: "It's half past ten.",
    image: "",
  },
  {
    id: "5",
    front: "Jest za kwadrans dziesiąta.",
    back: "It's a quarter to ten.",
    image: "",
  },
  {
    id: "6",
    front: "Jest kwadrans po dziesiątej.",
    back: "It's a quarter past ten.",
    image: "",
  },
  {
    id: "7",
    front: "Jest za dwadzieścia ósma.",
    back: "It's twenty to eight.",
    image: "",
  },
  {
    id: "8",
    front: "Jest dwadzieścia po dziewiątej.",
    back: "It's twenty past nine.",
    image: "",
  },
  {
    id: "9",
    front: "o siódmej",
    back: "at 7 o'clock",
    image: "",
  },
  {
    id: "10",
    front: "o siódmej rano",
    back: "at 7 am",
    image: "",
  },
  {
    id: "11",
    front: "o siódmej wieczorem",
    back: "at 7 pm",
    image: "",
  },
  {
    id: "12",
    front: "rano",
    back: "in the morning",
    image: "",
  },
  {
    id: "13",
    front: "po południu",
    back: "in the afternoon",
    image: "",
  },
  {
    id: "14",
    front: "wieczorem",
    back: "in the evening",
    image: "",
  },
  {
    id: "15",
    front: "w nocy",
    back: "at night",
    image: "",
  },
  {
    id: "16",
    front: "Mam spotkanie o ósmej.",
    back: "I have a meeting at 8 o'clock.",
    image: "",
  },
  {
    id: "17",
    front: "Mam spotkanie o ósmej wieczorem.",
    back: "I have a meeting at 8 pm.",
    image: "",
  },
  {
    id: "18",
    front: "Mam spotkanie o ósmej rano.",
    back: "I have a meeting at 8 am.",
    image: "",
  },
  {
    id: "19",
    front: "wcześnie",
    back: "early",
    image: "",
  },
  {
    id: "20",
    front: "późno",
    back: "late",
    image: "",
  },
  {
    id: "21",
    front: "Zaczynam pracę o dziewiątej.",
    back: "I start work at 9 o'clock.",
    image: "",
  },
  {
    id: "22",
    front: "Spotkajmy się o jedenastej.",
    back: "Let's meet at eleven.",
    image: "",
  },
  {
    id: "23",
    front: "Zjedzmy obiad po południu.",
    back: "Let's have lunch in the afternoon.",
    image: "",
  },
  {
    id: "24",
    front: "Jest dziesięć po drugiej.",
    back: "It's ten (minutes) past two.",
    image: "",
  },
  {
    id: "25",
    front: "Jest za dziesięć czwarta.",
    back: "It's ten (minutes) to four.",
    image: "",
  },
  {
    id: "26",
    front: "Jest pięć po piątej.",
    back: "It's five (minutes) past five.",
    image: "",
  },
  {
    id: "27",
    front: "Jest za pięć piąta.",
    back: "It's five (minutes) to five.",
    image: "",
  },
  {
    id: "28",
    front: "Jest prawie siódma.",
    back: "It's almost seven o'clock.",
    image: "",
  },
  {
    id: "29",
    front: "Jest już siódma.",
    back: "It's already seven.",
    image: "",
  },
  {
    id: "30",
    front: "Jeszcze nie jest za późno.",
    back: "It's not too late.",
    image: "",
  },
];

export const level2_1 = [
  {
    id: "2.1",
    level: "2",
    title: "Time",
    audio: "/audio/1_1_audio_loopcourse.mp3",
    cards: cards2_1,
  },
];
